source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

#Gem to use the tagging skill
gem 'acts-as-taggable-on', '~>2.1.0'

#Gem to access to imdb web service
gem 'movie_searcher'

#This gem generates a default web app theme
gem 'web-app-theme', '~> 0.8.0'

# Pagination with Kaminari
gem 'kaminari'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'


group :test, :development do
	gem 'rspec-rails', '>=2.7.0'
	gem 'cucumber-rails', '>=1.2.0'
	gem 'fakeweb'
	gem 'minitest', '>=2.7.0'
	gem 'capybara', '>=1.1.1'
end

group :development do
  gem 'annotate', :git => 'git://github.com/ctran/annotate_models.git'
	gem 'yard', '>=0.7.3'
end

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
	gem 'database_cleaner'
end
